apiVersion: v1
kind: Service
metadata:
  name: py-exporter
  namespace: monitoring
spec:
  selector:
    app: py-exporter
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: py-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: py-exporter
    spec:
      containers:
      - name: py-exporter
        image: py_exporter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000